### ISSUE TITLE
obsolete taxid check

### ISSUE THREAD

**Issue by msaavedrat** [shenwei356/taxonkit#10]
Hi :),
A little problem appears when the taxid gets "obsolet". However that info (and the new taxid), can be fetched from merged.dmp
I suggest you adding a little check in merged file, in case of no taxid be found? (Or search in merged first, something like that...). 
Example: taxid 92489 was replaced with 796334 (Erwinia oleae). I tested it with list function.
Thanks

**Comment by shenwei356** [comment]
Sorry for the late reply. What command did you use for this case? what's the purpose?

**Comment by msaavedrat** [comment]
Ok, It's not properly a bug, but a suggestion that could be a useful command/upgrade to check the id (if was modified recently, merged or deleted) in case of taxid was obtained from "old (not updated)" data, text, etc.
For example: 
taxonkit list --ids 92489 [result nothing.. So i must check that id]; when i search that id with web NCBI taxonomy, is redirected to the updated 796334 taxid and organism data (well expected). And of course, the command: taxonkit list --ids 796334 [it works perfectly]
That is because 92489 now is assigned to 796334 id (in merged.dmp).

**Comment by lskatz** [comment]
It might make sense to have a function in taxonkit called "clean" where you identify or remove nodes with no parent.

**Comment by shenwei356** [comment]
I'll fix this situation.

**Comment by shenwei356** [comment]
@msaavedrat we check deleted and merged taxids now. https://github.com/shenwei356/taxonkit/issues/19

**Comment by shenwei356** [comment]
I think v0.5.0 fixes this, can I close this issue now?

**Comment by shenwei356** [comment]
closed

**Comment by shenwei356** [comment]
close

**Comment by shenwei356** [comment]
~

**Comment by shenwei356** [comment]
~

**Comment by shenwei356** [comment]
.
