### ISSUE TITLE
Discrepency with default database and latest database

### ISSUE THREAD

**Issue by JonathanAbrahams1337** [shenwei356/taxonkit#101]
Hi,

I am using taxonkit lineage, and it works wonderfully so far. But there are a few species it seems not to be finding, despite their presence on the NCBI taxonomy portal.

I am not sure how the tool get the taxonomy database, but it seems to be that it might be operating on an old database?

I am interested in this species: 
[Orthorubulavirus laryngotracheitidis ](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=3052557&lvl=3&p=has_linkout&p=blast_url&p=genome_blast&lin=f&keep=1&srchmode=1&unlock) 3052557 

It doesnt find it when I use the tool and the database it is bundled with, and I can see with grep this is not in the default node file that comes with the tool. But this is present in the latest version of nodes/names and uasing this as a database using --data-dir does work.

Is it worth updating the database? In my use-case I have 4-5 taxids (all viruses) that are effected by this, so it isnt a one off!

https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz

**Comment by shenwei356** [comment]
Well, NCBI taxonomy changes frequently. See https://github.com/shenwei356/taxid-changelog

For `Orthorubulavirus laryngotracheitidis 3052557`, you can see it was created last July.

```
$ zcat taxid-changelog.csv.gz | csvtk grep -f taxid -p 3052557
taxid,version,change,change-value,name,rank,lineage,lineage-taxids
3052557,2023-07-01,NEW,,Orthorubulavirus laryngotracheitidis,species,Viruses;Riboviria;Orthornavirae;Negarnaviricota;Haploviricotina;Monjiviricetes;Mononegavirales;Paramyxoviridae;Rubulavirinae;Orthorubulavirus;Orthorubulavirus laryngotracheitidis,10239;2559587;2732396;2497569;2497570;2497574;11157;11158;2560080;2560195;3052557

```
TaxonKit's source data is the taxdump file you downloaded (`$HOME/.taxonkit`, so you might need to update it.
