### ISSUE TITLE
Feature request: viral realms

### ISSUE THREAD

**Issue by mdhishamshaikh** [shenwei356/taxonkit#102]
Hi,
I work on viral omics and I'm using your tool to get complete lineages out. I really like the function where I can get formatted lineages out. 
`
cut -f 2 updated_taxids.txt | taxonkit reformat -I 1 -f "{k},{K},{p},{c},{o},{f},{g},{s},{S},{T}" -F > lineage.txt
`
I wonder if you could consider adding viral realms as one of the placeholders.

Thank you!

Cheers,
Hisham

**Comment by shenwei356** [comment]
It's useful. I'll add it.

**Comment by shenwei356** [comment]
Try it.

- [taxonkit_linux_amd64.tar.gz](https://github.com/user-attachments/files/17096517/taxonkit_linux_amd64.tar.gz)
- [taxonkit_darwin_arm64.tar.gz](https://github.com/user-attachments/files/17096503/taxonkit_darwin_arm64.tar.gz)


E.g., using https://github.com/shenwei356/ictv-taxdump

```
# realm,kingdom,phylum,class,order,family,genus,species
$ echo 418966335 \
    | taxonkit reformat --data-dir ictv-taxdump -I 1 -f "{r};{K};{p};{c};{o};{f};{g};{s}"
418966335       Riboviria;Orthornavirae;Pisuviricota;Pisoniviricetes;Nidovirales;Coronaviridae;Betacoronavirus;Betacoronavirus hongkongense
```
