### ISSUE TITLE
Taxid to accession number

### ISSUE THREAD

**Issue by SergeyBaikal** [shenwei356/taxonkit#104]
### Prerequisites

- [0.8.0 ] make sure you're are using the latest version by `taxonkit version`
- [ yes] read the [usage](http://bioinf.shenwei.me/taxonkit/usage/)

### Describe your issue
Sorry, I can't find the commands to extract the accession number list by taxonomy id. Could you please help with this question?

`cat list_Tax_id_viruses_.txt`

I'm trying to get that output:

10786 AB000048 AB000049 AB000050 ...
1307956 AB000383 AB000920 ...

**Comment by shenwei356** [comment]
just use commands like `grep -w -f taxids  data.tsv` or csvtk (https://github.com/shenwei356/csvtk)
