### ISSUE TITLE
line-buffered output

### ISSUE THREAD

**Issue by tolot27** [shenwei356/taxonkit#11]
Currently, taxonkit uses xopen fully buffered output writers. Would it be possible to use at least a line-buffered writer? Grep does this by an additional parameter `--line-buffered`.
The rationale behind this request is the piping of BLASTs tabular output. BLAST is line-buffered and I can process hits as they "appear" but not with taxonkit. Long-running BLAST jobs piped to taxonkit will produce the output only if a lot of hits "appear", regardless of the Linux tools `unbuffer` or `stdbuf -oL`.

**Comment by shenwei356** [comment]
oh, it easy, will do it tonight.

**Comment by shenwei356** [comment]
try this: [v0.2.5-dev](https://github.com/shenwei356/taxonkit/releases/tag/v0.2.5-dev) with flag `--line-buffered` to disable output buffering.
