### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by IsmailM** [shenwei356/taxonkit#12]
Hey, 

Cool tool - have u published this? How should we cite this in our paper?

**Comment by shenwei356** [comment]
No, just cite the URL:  https://github.com/shenwei356/taxonkit/

**Comment by shenwei356** [comment]
you can cite this preprint now: https://www.biorxiv.org/content/early/2019/01/08/513523

**Comment by IsmailM** [comment]
Cool preprint 👍 

Our paper has been accepted and so not sure if I can change the citation at this stage - regardless if I get a chance to add this (i.e. during proofs), I will do so...

**Comment by shenwei356** [comment]
Congrats!
