### ISSUE TITLE
Now in Brew

### ISSUE THREAD

**Issue by tseemann** [shenwei356/taxonkit#15]
I made this work:

```
brew install brewsci/bio/taxonkit
```

**Comment by shenwei356** [comment]
Thank you Torsten!

**Comment by tseemann** [comment]
It's also already in Conda:  `brew install -c bioconda taxonkit`

**Comment by sjackman** [comment]
`brew install -c bioconda taxonkit`
I think you mean `conda install -c bioconda taxonkit` 😉
