### ISSUE TITLE
$TAXONKIT_DB variable for file locations?

### ISSUE THREAD

**Issue by tseemann** [shenwei356/taxonkit#17]
```
And copy "names.dmp" and "nodes.dmp" to data directory: "$HOME/.taxonkit".
```

We use taxonkit on a shared server with many users.

Would you be able to honour an env variable like `$TAXONKIT_DB` so that we can put the files in one place that's not a home directory?

Then we can have global `export TAXONKIT_DB=/opt/data/taxonkit/` and the two files will be found there?

We'd rather not set global aliases for `--names-file` and `--nodes-file`

**Comment by shenwei356** [comment]
Sure, I'll implement this in few days.

**Comment by shenwei356** [comment]
Dear @tseemann , please test it. [v0.2.5-dev4](https://github.com/shenwei356/taxonkit/releases/edit/v0.2.5-dev4)
