### ISSUE TITLE
Adding and removing nodes

### ISSUE THREAD

**Issue by lskatz** [shenwei356/taxonkit#18]
### Prerequisites

- [x] make sure you're are using the latest version by `taxonkit version`
  * Version 0.3.0
- [x] read the [usage](http://bioinf.shenwei.me/taxonkit/usage/)

### Describe your issue

* [x] describe the problem
  * I was wondering if you could add new subcommands for adding/removing nodes.  I am suggesting the subcommands 'touch' and 'rm' based on unix executables.
* [x] provide a reproducible example
  * `taxonkit touch 662 "Vibrio newspecies" #=> adds a new species under taxon id 662 with scientific name "Vibrio newspecies."  Prints the new taxon id.`
  * `taxonkit rm 662 #=> deletes node 662 and all nodes under it. Prints the number of nodes deleted.`

**Comment by lskatz** [comment]
To be clear, I know that the taxonomy files are read only. I was wondering if these proposed commands could export a new set of files.

**Comment by shenwei356** [comment]
Sorry for late response, I've got no idea.

You can edit the nodes.dmp or names.dump files if you like.
