### ISSUE TITLE
Why require delnodes.dmp and merged.dmp?

### ISSUE THREAD

**Issue by nick-youngblut** [shenwei356/taxonkit#27]
I created a tool for converting the Genomes Taxonomy DataBase (GTDB) taxonomy to nodes.dmp & names.dmp files. The tool is [gtdb_to_taxdump](https://github.com/nick-youngblut/gtdb_to_taxdump). The output works with `taxonkit<0.5.0`, but fails for `taxonkit>=0.5.0`, since you now require delnodes.dmp and merged.dmp. Why do you require these files? Could an option be included to override that requirement or is it absolutely necessary for taxonkit 0.5 to work?

**Comment by shenwei356** [comment]
Because we'd like to detect merged or deleted taxids, see #19 .

I can make it optional. You can also try again by creating empty delnodes.dmp merged.dmp .

**Comment by nick-youngblut** [comment]
Thanks for the quick reply! I tried just creating empty delnodes.dmp and merged.dmp files, but I then get a "file empty" error.

**Comment by shenwei356** [comment]
try adding a line staring with `#`

**Comment by nick-youngblut** [comment]
That works as long as the file contains `#\n`. Thanks!

**Comment by shenwei356** [comment]
fixed:

- [taxonkit_darwin_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/3820525/taxonkit_darwin_amd64.tar.gz)
- [taxonkit_linux_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/3820526/taxonkit_linux_amd64.tar.gz)
- [taxonkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/taxonkit/files/3820527/taxonkit_windows_amd64.exe.tar.gz)
