### ISSUE TITLE
Taxon ID instead of names in lineage

### ISSUE THREAD

**Issue by AsmaTahir** [shenwei356/taxonkit#3]
Hi there,

I would like to deduce the taxon ID#s instead of names in lineage. Is it possible? The documentation didn't describe it.

Thanks!

**Comment by shenwei356** [comment]
I've added it as the third column in the output of `taxonkit lineage`.

Check [v0.1.8-dev](https://github.com/shenwei356/taxonkit/releases/tag/v0.1.8-dev) or later versions.

**Comment by AsmaTahir** [comment]
Great. Thanks!
