### ISSUE TITLE
JSON output is malformed when running `taxonkit list`

### ISSUE THREAD

**Issue by standage** [shenwei356/taxonkit#30]
Adding the `--json` flag to the example included in the documentation for [taxonkit list](https://bioinf.shenwei.me/taxonkit/usage/#list) produces output that is not well-formed JSON.

```
$ taxonkit list --json --ids 9605,239934 > result.json
```

This can be confirmed with a JSON linter like https://jsonlint.com/ or, as I discovered it, with Python's JSON parser.

```python
>>> import json
>>> with open('result.json') as fh:
...   result = json.load(fh)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/standage/anaconda3/envs/taxonkit/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/standage/anaconda3/envs/taxonkit/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/standage/anaconda3/envs/taxonkit/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/standage/anaconda3/envs/taxonkit/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 13 column 5 (char 149)
>>>
```

----------

### Prerequisites

- [x] make sure you're are using the latest version by `taxonkit version`
- [x] read the [usage](http://bioinf.shenwei.me/taxonkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

**Comment by shenwei356** [comment]
fixed:

- [taxonkit_darwin_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/4547453/taxonkit_darwin_amd64.tar.gz)
- [taxonkit_linux_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/4547454/taxonkit_linux_amd64.tar.gz)
- [taxonkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/taxonkit/files/4547455/taxonkit_windows_amd64.exe.tar.gz)

**Comment by standage** [comment]
Looks great—I confirmed it's working on my end. Thanks!

**Comment by standage** [comment]
I'm working on Python bindings for TaxonKit. Please let me know when a bugfix release is available from bioconda.

**Comment by shenwei356** [comment]
In 1-2 day.
