### ISSUE TITLE
taxonkit reformat omits species for some species taxids

### ISSUE THREAD

**Issue by Shellfishgene** [shenwei356/taxonkit#31]
Hi!

The following command does not output the species, I'm not sure why. Is this a bug or related to the taxonomy of this species in NCBI?

```
echo '272799' | taxonkit lineage --data-dir $BLASTDB | taxonkit --data-dir $BLASTDB reformat | csvtk -tH cut -f 1,3              
272799  Eukaryota;Chordata;Mammalia;Chiroptera;Vespertilionidae;Plecotus;
```
The full output of the taxon using
```
echo '272799' | taxonkit lineage --data-dir $BLASTDB
``` 
ends correctly with the species, ```Plecotus gaisleri```.
More example taxids where this happens: ```2493713, 1629512, 602068```

Thanks for all the nice programs!

**Comment by shenwei356** [comment]
is 272799 species? check rank with taxonkit lineage -r

**Comment by Shellfishgene** [comment]
Ah, it's a subspecies, and there is no species. I didn't know that existed, does not make much sense to me. So it's just NCBI, thanks!
