### ISSUE TITLE
Possible bug with taxonkit filter --black-list

### ISSUE THREAD

**Issue by standage** [shenwei356/taxonkit#37]
When user specifies a rank or a (comma separated?) list of ranks for `--black-list`, these should be excluded from the output, correct? I have tried the following example several times with different ranks, and I get the same error message every time.

```
$ echo 349741 | taxonkit lineage -t | cut -f 3 | sed 's/;/\n/g' > taxids2.txt
$ cat taxids2.txt | taxonkit filter -B Family 
23:40:47.905 [ERRO] rank order not defined in rank file: no rank
```

Is this a bug, or am I misunderstanding this flag?

----------

### Prerequisites

- [x] make sure you're are using the latest version by `taxonkit version`
- [x] read the [usage](http://bioinf.shenwei.me/taxonkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

**Comment by shenwei356** [comment]
You have to leave the default value in the black list. I should have maken it clear.

```
cat taxids2.txt | taxonkit filter -B Family -B "no rank,clade"
2
74201
203494
48461
1647988
239934
239935
349741
```

**Comment by standage** [comment]
For now, the Python bindings add "no rank" and "clade" to the blacklist automatically, and it works ok.

But if it is required to leave the default values in the blacklist, maybe the `--black-list` flag should append to the list instead of replace it?

**Comment by shenwei356** [comment]
I read the code again, and fix the logic. 

"no rank" and "clade" are already defined as ranks with no order in the ranks.txt, and they can be optional removed via `--discard-noranks`,  `-B/--blast-list` can be used for adding more ranks to delete, it can also include "no rank".

```
  -B, --black-list strings   black list of ranks to discard, e.g., '"no rank", "clade"'
  -N, --discard-noranks      discard ranks without order, type "taxonkit filter --help" for details
```

```
  1. Flag -L/--lower-than and -H/--higher-than are exclusive, and can be
     used along with -E/--equal-to which values can be different.
  2. A list of pre-ordered ranks is in ~/.taxonkit/ranks.txt, you can use
     your list by -r/--rank-file, the format specification is below.
  3. All ranks in taxonomy database should be defined in rank file.
  4. TaxIDs with no rank can be optionally discarded by -N/--discard-noranks.
  5. Futher ranks can be removed with black list via -B/--black-list.
```

**Comment by shenwei356** [comment]
- [taxonkit_darwin_arm64.tar.gz](https://github.com/shenwei356/taxonkit/files/5853936/taxonkit_darwin_arm64.tar.gz)
- [taxonkit_linux_arm64.tar.gz](https://github.com/shenwei356/taxonkit/files/5853937/taxonkit_linux_arm64.tar.gz)

**Comment by standage** [comment]
Oh, ok. So if I want to specify `-B family` then the `-N` flag is required?

**Comment by shenwei356** [comment]
not required, it's optional. -N is just for removing "no rank", "clade".

**Comment by standage** [comment]
If it's optional, why did my original command fail?

**Comment by shenwei356** [comment]
There was a bug, it's fixed now.

**Comment by standage** [comment]
Oh ok. 🤓

**Comment by standage** [comment]
Is it easy for you to create a Darwin AMD binary? Don't worry if it's inconvenient.

**Comment by shenwei356** [comment]
Oh, I wrongly uploaded arm64 binaries...

- [taxonkit_darwin_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/5856635/taxonkit_darwin_amd64.tar.gz)
- [taxonkit_linux_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/5856638/taxonkit_linux_amd64.tar.gz)

**Comment by standage** [comment]
Ok, I understand now. And I confirmed that my original command works. Thank you!
