### ISSUE TITLE
Difference between `--list-order` and `--list-ranks` unclear

### ISSUE THREAD

**Issue by standage** [shenwei356/taxonkit#38]
For the new `taxonkit filter` command, I'm not sure what the difference is between the `--list-ranks` and `--list-order` flags. I can see that `--list-order` is more comprehensive. Can you explain the difference? Thank you for your patience! 😄

**Comment by shenwei356** [comment]
```
      --list-order           list defined ranks in order
      --list-ranks           list ordered ranks in taxonomy database
```

` --list-order` is for listing user defined ranks in `$HOME/.taxonkit/ranks.txt`.

`--list-ranks` is for listing ranks in taxonomy database, which are sorted in user defined order. And all ranks in DB should be defined `$HOME/.taxonkit/ranks.txt`.

Is it clear? :)

**Comment by standage** [comment]
Yes, that helps, thanks!

**Comment by shenwei356** [comment]
Some ranks in `$HOME/.taxonkit/ranks.txt` may be not appeared in current version of NCBI taxonomy database. I tried to cover al possible values. Most are from https://en.wikipedia.org/wiki/Taxonomic_rank .
