### ISSUE TITLE
Unsure about usage of --pseudo-strain

### ISSUE THREAD

**Issue by standage** [shenwei356/taxonkit#40]
Consider the following two commands.

```
$ echo 36827 | taxonkit lineage | taxonkit reformat --add-prefix --format '{k};{p};{c};{o};{f};{g};{s};{T}'
36827   cellular organisms;Bacteria;Terrabacteria group;Firmicutes;Clostridia;Clostridiales;Clostridiaceae;Clostridium;Clostridium botulinum;Clostridium botulinum B        k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Clostridiaceae;g__Clostridium;s__Clostridium botulinum;T__
$ echo 36827 | taxonkit lineage | taxonkit reformat --add-prefix --format '{k};{p};{c};{o};{f};{g};{s};{T}' --pseudo-strain
36827   cellular organisms;Bacteria;Terrabacteria group;Firmicutes;Clostridia;Clostridiales;Clostridiaceae;Clostridium;Clostridium botulinum;Clostridium botulinum B        k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Clostridiaceae;g__Clostridium;s__Clostridium botulinum;T__
```

The lowest taxon in this lineage is below species and has no rank, so I expected the `--pseudo-strain` to report the name of this taxon as the strain. It doesn't work with `{T}` or `{t}`. Am I doing something wrong?

----------

### Prerequisites

- [x] make sure you're are using the latest version by `taxonkit version`
- [x] read the [usage](http://bioinf.shenwei.me/taxonkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

**Comment by shenwei356** [comment]
missing `-F` :)

**Comment by shenwei356** [comment]
I improve the flag checking.

    if `{t}/{S}/{T}` found in `--format` {
        if `-S/--pseudo-strain` is on, but `-F/--fill-miss-rank` not given {
            log.info()
            turn on `-F`
        }  
    } else if `-S/--pseudo-strain` is on {
        log.warning()
    }

Example:


    $ echo 36827 \
            | taxonkit lineage \
            | taxonkit reformat --add-prefix --format '{g};{s};{t}'  --pseudo-strain --fill-miss-rank \
            | cut -f 1,3
    36827   g__Clostridium;s__Clostridium botulinum;t__Clostridium botulinum B

    $ echo 36827 \
        | taxonkit lineage \
        | taxonkit reformat --add-prefix --format '{g};{s};{t}'  --pseudo-strain \
        | cut -f 1,3
    08:36:01.750 [INFO] -F/--fill-miss-rank is switched on when giving flag -S/--pseudo-strain
    36827   g__Clostridium;s__Clostridium botulinum;t__Clostridium botulinum B
    
    $ echo 36827 \
        | taxonkit lineage \
        | taxonkit reformat --add-prefix --format '{g};{s}'  --pseudo-strain \
        | cut -f 1,3
    08:35:01.515 [WARN] flag -S/--pseudo-strain will not work because none of "{t}", "{S}", "{T}" is found in -f/--format
    36827   g__Clostridium;s__Clostridium botulinum

**Comment by standage** [comment]
Thanks.
