### ISSUE TITLE
reformat should support tab characters in format string

### ISSUE THREAD

**Issue by tolot27** [shenwei356/taxonkit#5]
It would be great if `reformat` would support tab characters in the format string to separate the placeholders into separate columns.

It tried to provide tabs with `\t` like following:

```
taxonkit reformat -f "{k}\t{p}\t{c}\t{o}\t{f}\t{g}\t{s}\t{S}"
```
An intermediate solution is to mask the string in bash like `$'{k}\t{p}\t{c}\t{o}\t{f}\t{g}\t{s}\t{S}'`. But that's not obvious to most users.

**Comment by shenwei356** [comment]
Thanks for your suggestion, it's supported now in [v0.2.4-dev](https://github.com/shenwei356/taxonkit/releases/tag/v0.2.4-dev).

Please try it and any feedback is welcome.
