### ISSUE TITLE
Taxonkit list tabular output

### ISSUE THREAD

**Issue by MichWeb75** [shenwei356/taxonkit#51]
Hi,
I would like to generate a tab separated output for further processing:
The following output contains only spaces which makes it difficult to separate columns.

`taxonkit list --ids 2157 -n -r --indent "" > archae_tree.txt`

Is there an option like 
sep = "\t" ?

Best, Michael

**Comment by shenwei356** [comment]
Pipe to `taxonkit lineage`, see example 5.
https://bioinf.shenwei.me/taxonkit/usage/#lineage

**Comment by MichWeb75** [comment]
Works! Perfect, thank you
