### ISSUE TITLE
"out of range" error for Reformat on long taxonomic strings

### ISSUE THREAD

**Issue by mycowx** [shenwei356/taxonkit#52]
### Prerequisites

- [X] make sure you're are using the latest version by `taxonkit version`
- [X] read the [usage](http://bioinf.shenwei.me/taxonkit/usage/)

### Describe your issue

* [X] describe the problem
Receive an "out of range" error when using reformat option on certain taxa.  See example below for TaxID 101020

* [X] provide a reproducible example
```
> echo 101020 | taxonkit lineage -
101020  cellular organisms;Eukaryota;Viridiplantae;Streptophyta;Streptophytina;Embryophyta;Tracheophyta;Euphyllophyta;Spermatophyta;Magnoliopsida;Mesangiospermae;eudicotyledons;Gunneridae;Pentapetalae;rosids;fabids;Rosales;Rosaceae;Rosoideae;Potentilleae;Fragariinae;Fragaria;Fragaria vesca;Fragaria vesca subsp. vesca

> echo 101020 | taxonkit reformat -
11:51:03.201 [ERRO] lineage-field (2) out of range (1):101020
```

**Comment by shenwei356** [comment]
Add `-I 1`

https://bioinf.shenwei.me/taxonkit/usage/#reformat

**Comment by mycowx** [comment]
Oops.. My bad.  Thanks.
