### ISSUE TITLE
[Question] How to get specific taxonomic fields (not full taxonomy string) from a list of taxon identifiers?

### ISSUE THREAD

**Issue by jolespin** [shenwei356/taxonkit#53]
### Prerequisites

- [ X] make sure you're are using the latest version by `taxonkit version`
- [ X] read the [usage](http://bioinf.shenwei.me/taxonkit/usage/)

### Describe your issue
What is the recommended method for getting only a subset of lineages with `taxonkit lineage`? 
e.g., `superkingdom,phylum,order,class,family,genus,species`

* [ ] describe the problem
I made a post-processing script that puts it into the following format with prefixes:
`["superkingdom", "phylum", "class", "order", "family", "genus", "species"], ["d__","p__","c__","o__","f__","g__","s__"])`

This is what GTDB-Tk uses and I need to manually create this for a few taxa. 

* [ ] provide a reproducible example

For example, with the following file called `euk.list`: 

```
$ cat euk.list
425265
76775
```

If I run `taxonkit lineage -R -t euk.list`, I get the following output: 

```
425265	cellular organisms;Eukaryota;Opisthokonta;Fungi;Dikarya;Basidiomycota;Ustilaginomycotina;Malasseziomycetes;Malasseziales;Malasseziaceae;Malassezia;Malassezia globosa;Malassezia globosa CBS 7966	131567;2759;33154;4751;451864;5204;452284;1538075;162474;742845;55193;76773;425265	no rank;superkingdom;clade;kingdom;subkingdom;phylum;subphylum;class;order;family;genus;species;strain
76775	cellular organisms;Eukaryota;Opisthokonta;Fungi;Dikarya;Basidiomycota;Ustilaginomycotina;Malasseziomycetes;Malasseziales;Malasseziaceae;Malassezia;Malassezia restricta	131567;2759;33154;4751;451864;5204;452284;1538075;162474;742845;55193;76775	no rank;superkingdom;clade;kingdom;subkingdom;phylum;subphylum;class;order;family;genus;species
```

**Comment by shenwei356** [comment]
check https://bioinf.shenwei.me/taxonkit/usage/#reformat

**Comment by jolespin** [comment]
Wow, you really did think of everything!  Awesome. `seqkit` and `taxonkit` still amaze me on what they can handle. This will speed up my workflow a lot (guess I have to toss all the code I wrote reinventing the wheel earlier). 

```
taxonkit lineage -R -t euk.list  | taxonkit reformat --prefix-k d__ --prefix-p p__ --prefix-c c__ --prefix-o o__ --prefix-f f__ --prefix-g g__ --prefix-s s__ -P > euk_lineage.tsv
```

**Comment by shenwei356** [comment]
If you already have TaxIds, there's no need to run `lineage` before `reformat`.

`reformat` accepts input of TaxIds via flag ` -I/--taxid-field`. Check the example 1.

**Comment by jolespin** [comment]
> reformat accepts input of TaxIds via flag -I/--taxid-field. Check the example 1.

Can it accept from stdin?

**Comment by shenwei356** [comment]
of cause, it does.
