### ISSUE TITLE
Taxonkit Bash-completion terminal error

### ISSUE THREAD

**Issue by divya1srv** [shenwei356/taxonkit#54]
Hello,

I installed latest version of Taxonkit from github using "Bash-completion" method.
Query: After installation when I relogin on the server using terminal I got following below message:
 **"-bash: /home/bioinfo/.bash_completion.d/*: No such file or directory:"**
On every login I get this message, and unable to use software. So, I also uninstalled the taxonkit. 
But then also the same message comes on every login.
Kindly suggest me how I can solve this error message. 

Thank you.

**Comment by shenwei356** [comment]
Just make one:

    mkdir ~/.bash_completion.d
