### ISSUE TITLE
`create-taxdump` ignores the class rank

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/taxonkit#57]
taxdumps created with `create-taxdump` don't have the class rank. To reproduce, follow the steps in [`ictv-taxdump`](https://github.com/shenwei356/ictv-taxdump) and check the `names.dmp` file. It won't contain classes:

```
rg "Tokiviricetes" ictv-taxdump/names.dmp
```

I tested with a custom dataset (also based on the ICTV table) and had the same issue.

**Comment by apcamargo** [comment]
It seems the error is here:

```go
			if hasClass {
				val = (*items)[fClass-1]
				if _, ok = nullMap[val]; !ok {
					t.Class = val

					t.Names[3] = t.Order
					t.TaxIds[3] = uint32(xxhash.Sum64String(strings.ToLower(t.Order)))
				}
			}
```

I guess it should be `t.Names[2] = t.Class`

**Comment by shenwei356** [comment]
Yes, It's a bug during copy and paste. Thank you @apcamargo

**Comment by shenwei356** [comment]
also tagged a new version for ictv-taxdump: https://github.com/shenwei356/ictv-taxdump/releases/tag/v0.1.1

**Comment by shenwei356** [comment]
Please test the patch, if there are no more bugs, I'll tag a new release.

- [taxonkit_linux_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/8735984/taxonkit_linux_amd64.tar.gz)
- [taxonkit_darwin_arm64.tar.gz](https://github.com/shenwei356/taxonkit/files/8735983/taxonkit_darwin_arm64.tar.gz)
- [taxonkit_darwin_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/8735982/taxonkit_darwin_amd64.tar.gz)

**Comment by apcamargo** [comment]
Worked as expected. Thank you!
