### ISSUE TITLE
Is it expected to have different output from reformat depending on whether the input are only tax IDs or a lineage table?

### ISSUE THREAD

**Issue by Midnighter** [shenwei356/taxonkit#62]
### Prerequisites

- [x] `taxonkit v0.12.0`
- [x] read the [usage](http://bioinf.shenwei.me/taxonkit/usage/)

### Describe your issue

I want to create a simplified taxonomy of all fungi. It seems that with the latest version of taxonkit, I have two options:

1. Create a lineage file from a bunch of taxonomy IDs and then reformat it.

    ```bash
    taxonkit list --ids 4751 --indent "" | \
        taxonkit lineage | \
        taxonkit reformat \
        --taxid-field 1 \
        --fill-miss-rank \
        --output-ambiguous-result \
        --add-prefix \
        --show-lineage-taxids \
        --format "{k};{p};{c};{o};{f};{g};{s}"
    ```

    First line of the output:

    ```tsv
    4751	cellular organisms;Eukaryota;Opisthokonta;Fungi	k__Eukaryota;p__unclassified Eukaryota phylum;c__unclassified Eukaryota class;o__unclassified Eukaryota order;f__unclassified Eukaryota family;g__unclassified Eukaryota genus;s__unclassified Eukaryota species	2759;;;;;;
    ```

2. Alternatively, I can directly use the identifiers as input to reformat.

    ```bash
    taxonkit list --ids 4751 --indent "" | \
        taxonkit reformat \
        --taxid-field 1 \
        --fill-miss-rank \
        --output-ambiguous-result \
        --add-prefix \
        --show-lineage-taxids \
        --format "{k};{p};{c};{o};{f};{g};{s}"
    ```

    First line of the output:

    ```tsv
    4751	k__Eukaryota;p__unclassified Eukaryota phylum;c__unclassified Eukaryota class;o__unclassified Eukaryota order;f__unclassified Eukaryota family;g__unclassified Eukaryota genus;s__unclassified Eukaryota species	2759;;;;;;
    ```

**Comment by shenwei356** [comment]
Yes, you found it. In the beginning, `reformat` only accept full lineage as input. In detail, it used one node and its parent node to get the taxId, however, [this brought some errors for some taxa](https://github.com/shenwei356/taxonkit/issues/42). So, after v0.8.0, it accepts input of TaxIds via flag `-I/--taxid-field`.

**Comment by Midnighter** [comment]
Sorry, my question here is from the title, is it expected that the information output differs between the two? Probably yes, as additional columns from the lineage file are preserved.
