### ISSUE TITLE
Sequence names starting with "Sp_"

### ISSUE THREAD

**Issue by snayfach** [shenwei356/taxonkit#65]
I built a taxdump using a custom taxonomy with the command:
`taxonkit create-taxdump genome_taxonomy.tsv -A 1 -O out--force`

A few of the accessions in `genome_taxonomy.tsv` start with "Sp_" and I noticed this prefix was removed in the `taxid.map` output file causing some issues.

I'll find a workaround, but thought you might want to know

**Comment by shenwei356** [comment]
Thank you, Stephen. 

There's a bug when using the command you use. Didn't it occur?
I've fixed it but haven't released it yet. Please use the binary here:

- [taxonkit_darwin_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/9600056/taxonkit_darwin_amd64.tar.gz)
- [taxonkit_darwin_arm64.tar.gz](https://github.com/shenwei356/taxonkit/files/9600063/taxonkit_darwin_arm64.tar.gz)
- [taxonkit_linux_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/9600065/taxonkit_linux_amd64.tar.gz)

```
- fix bug of handling non-GTDB data when using `-A/--field-accession` and no rank names given.
```

**Comment by shenwei356** [comment]
I figure out what happend. Please wait for a few minutes.

**Comment by shenwei356** [comment]
Fixed. The old default regular expression `^\w\w_(.+)$` wrongly removed the `Sp_` prefix, which is meant to remove the prefix `GB_` or `RS_` of `GB_GCA_001941065.1` in GTDB taxnomy data. Now it's changed:

```
--field-accession-re string       regular expression to extract assembly accession (default "^(.+)$")
```

- [taxonkit_linux_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/9600463/taxonkit_linux_amd64.tar.gz)
- [taxonkit_darwin_arm64.tar.gz](https://github.com/shenwei356/taxonkit/files/9600462/taxonkit_darwin_arm64.tar.gz)
- [taxonkit_darwin_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/9600460/taxonkit_darwin_amd64.tar.gz)

**Comment by snayfach** [comment]
Thanks! Trying now... A quick unrelated question I was hoping you could answer: how should I format the input file for sequences that are unclassified at a given rank? Can I use "unclassified" or an empty string "" or do I need to include the parent taxon e.g. "unclassified_proteobacteria"?
