### ISSUE TITLE
panic: runtime error: index out of range [4] with length 4

### ISSUE THREAD

**Issue by Summer0lhl** [shenwei356/taxonkit#66]
hello，when using any taxonkit commond, got following errors.
`
 $taxonkit list --ids 9606 --indent ""
panic: runtime error: index out of range [4] with length 4

goroutine 17 [running]:
github.com/shenwei356/taxonkit/taxonkit/cmd.stringSplitN({0xc004423c20, 0xc0004160ef}, {0x850d88, 0x1}, 0x8, 0xc000376e30)
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/taxonkit/taxonkit/cmd/util.go:41 +0x1de
github.com/shenwei356/taxonkit/taxonkit/cmd.getTaxonNames({0xc0000301a0, 0x0})
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/taxonkit/taxonkit/cmd/util-basic-data.go:121 +0x191
github.com/shenwei356/taxonkit/taxonkit/cmd.loadData.func2()
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/taxonkit/taxonkit/cmd/util-basic-data.go:71 +0x10e
created by github.com/shenwei356/taxonkit/taxonkit/cmd.loadData
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/taxonkit/taxonkit/cmd/util-basic-data.go:67 +0x23b
`

**Comment by shenwei356** [comment]
Sorry to hear this, have you chech the integrity of taxdump.tar.gz? Does the decompression process reports any error? Can you please redownload it?
