### ISSUE TITLE
`taxonkit lineage` stalls if taxID = 1

### ISSUE THREAD

**Issue by nick-youngblut** [shenwei356/taxonkit#7]
I'm using `taxonkit` v0.2.0 (installed via bioconda), and I was running `taxonkit lineage` on the "hits" file generated by `centrifuge`. `taxonkit lineage` would very quickly write out taxonomies for the first ~60000 hits, but then stall and the memory used would climb to >300 GB. It turns out that one of the centrifuge hits had a taxID of "1" (centifuge called this a "no rank"). I filtered out this "no rank" hits, which fixed this stalling issue.

**Comment by shenwei356** [comment]
fixed in [v0.2.4-dev2](https://github.com/shenwei356/taxonkit/releases/tag/v0.2.4-dev2)
