### ISSUE TITLE
Error with makeblastdb using GTDB taxonkit create-taxdump taxid.map

### ISSUE THREAD

**Issue by BenjaminJPerry** [shenwei356/taxonkit#70]
Hello Wei Shen,

This is not strictly an error with taxonkit create-taxdump, but more of a feature request?

I'm trying to use the taxid.map generated using taxonkit create-taxdump for the GTDB database (r207) when making a blastn database of the complete set of GTDB representative genomes (r207).

Making the taxdump using taxonkit,
```
(/home/perrybe/conda-envs/taxonkit) inscrutable$ taxonkit --help | head
TaxonKit - A Practical and Efficient NCBI Taxonomy Toolkit

Version: 0.13.0

Author: Wei Shen <shenwei356@gmail.com>

Source code: https://github.com/shenwei356/taxonkit
Documents  : https://bioinf.shenwei.me/taxonkit
Citation   : https://www.sciencedirect.com/science/article/pii/S1673852721000837

(/home/perrybe/conda-envs/taxonkit) inscrutable$ taxonkit create-taxdump --gtdb --force ar53_taxonomy.tsv bac120_taxonomy.tsv -O ./
09:02:31.932 [INFO] 317542 records saved to taxid.map
09:02:32.366 [INFO] 401815 records saved to nodes.dmp
09:02:32.642 [INFO] 401815 records saved to names.dmp
09:02:32.644 [INFO] 0 records saved to merged.dmp
09:02:32.644 [INFO] 0 records saved to delnodes.dmp

```

Using it to make the blast database (where the error occurs),
```
(/dataset/bioinformatics_dev/active/conda-env/blast2.9) inscrutable$ makeblastdb -version
makeblastdb: 2.9.0+
 Package: blast 2.9.0, build May 31 2019 20:53:30

(/dataset/bioinformatics_dev/active/conda-env/blast2.9) inscrutable$ makeblastdb -in GTDB-latest.fna -dbtype nucl -parse_seqids -taxid_map taxid.map


Building a new DB, current time: 11/24/2022 08:56:25
New DB name:   /bifo/scratch/2022-BJP-GTDB_Benchmarking/gtdb-latest/GTDB-latest.fna
New DB title:  GTDB-latest.fna
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Error: NCBI C++ Exception:
    T0 "/opt/conda/conda-bld/blast_1559335677723/work/c++/src/corelib/ncbistr.cpp", line 578: Error: ncbi::NStr::StringToInt() - Cannot convert string '2988443261' to int, overflow (m_Pos = 0)

```
In the taxid.map generated with taxonkit ,

```
(/dataset/bioinformatics_dev/active/conda-env/blast2.9) inscrutable$ cat taxid.map | wc -l
317542
(/dataset/bioinformatics_dev/active/conda-env/blast2.9) inscrutable$ cat taxid.map | grep -n "2988443261"
4:GCF_000980105.1       2988443261
(/dataset/bioinformatics_dev/active/conda-env/blast2.9) inscrutable$ head taxid.map
GCF_000979375.1 1349515035
GCF_000970165.1 1457399847
GCF_000979555.1 732503645
GCF_000980105.1 2988443261 <---
GCF_000007065.1 369781300
GCF_000980175.1 148096987
GCF_000970205.1 3005035806
GCA_002506415.1 1847834409
GCF_000970245.1 977990156
GCF_000970185.1 3122581739

```
It seems like the size of the value is too large for makeblastdb to handle when building?

It may be more of an issue with makeblastdb, but I thought I would pass it on as it might be an easy fix in taxonkit 😋

Thank you for all the excellent bioinformatic software 🥇 😁

Ben

**Comment by shenwei356** [comment]
We hashed the taxon name (in lower case) of each taxon node to uint64 using [xxhash](https://github.com/cespare/xxhash/) and converted it to `uint32` (max value: `(1<<32) - 1 = 4294967295`). While it looks like more than one tools store a taxid as an `int32` (max value: `(1<<31) - 1 = 2147483647`). 

It's time to change.

**Comment by shenwei356** [comment]
Just updated the code. Please test it.

- [taxonkit_linux_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/10084485/taxonkit_linux_amd64.tar.gz)
- [taxonkit_darwin_arm64.tar.gz](https://github.com/shenwei356/taxonkit/files/10084484/taxonkit_darwin_arm64.tar.gz)
- [taxonkit_darwin_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/10084494/taxonkit_darwin_amd64.tar.gz)

I'll update https://github.com/shenwei356/gtdb-taxdump later.

**Comment by shenwei356** [comment]
Tagged a new release:[ v0.14.0](https://github.com/shenwei356/taxonkit/releases/tag/v0.14.0)
