### ISSUE TITLE
Feature request: accession2taxid

### ISSUE THREAD

**Issue by stas-malavin** [shenwei356/taxonkit#74]
Hi, I'd love to have a possibility to assign taxid's to accession numbers locally using NCBI's ```nucl_gb.accession2taxid.gz```, ```nucl_wgs.accession2taxid.gz```, and ```prot.accession2taxid.gz```. This is possible with an ```R``` package [taxonomizr](https://cran.r-project.org/web/packages/taxonomizr/readme/README.html).

**Comment by shenwei356** [comment]
[csvtk](https://github.com/shenwei356/csvtk) is enough for mapping accession2taxid.

Retrieving accession2taxid data of accessions of interest.

```

cat prot.accession2taxid.gz \
    | csvtk grep -t -f accession.version -P acc.txt  \
    | csvtk cut -t -f accession.version,taxid  \
    | csvtk del-header -t \
    > prot.accession2taxid.tsv \
```

Quering taxid for each accession.

```
cat data.tsv \
    | csvtk mutate -H -t -f 1 \
    | csvtk replace -H -t -k prot.accession2taxid.tsv -p '(.+)' -r '{kv}' 
```

**Comment by stas-malavin** [comment]
That's beautiful, thank you! I really need to master [csvtk](https://github.com/shenwei356/csvtk)!
