### ISSUE TITLE
kraken2 report to mpa with counts

### ISSUE THREAD

**Issue by motroy** [shenwei356/taxonkit#83]
Hi @shenwei356 ,

thank you for this great tool! in your tutorial (https://bioinf.shenwei.me/taxonkit/tutorial/#parsing-krakenbracken-result) you show how to parse kraken2 report files to mpa style output with relative abundances - is it possible to generate the same mpa style output with the actual counts instead of relative abundance? If it is possible, I would really appreciate an example of doing so

thanks again,
regards,
Yair

**Comment by shenwei356** [comment]
```
$ cat SRS014459-Stool.fasta.gz_bracken_species.kreport \
    | csvtk cut -Ht -f 5,1 \                                             # here change "5,1" to "5,2"
    | taxonkit lineage \
    | taxonkit reformat -i 3 -P -f "{k}|{p}|{c}|{o}|{f}|{g}|{s}" \
    | csvtk cut -Ht -f 4,2 \
    | csvtk replace -Ht -p "(\|[kpcofgs]__)+$" \
    | csvtk replace -Ht -p "\|[kpcofgs]__\|" -r "|" \
    | csvtk uniq -Ht \
    | csvtk grep -Ht -p k__ -v \
    > SRS014459-Stool.fasta.gz_bracken_species.kreport.format
```
