### ISSUE TITLE
Search equivalent names with name2taxid?

### ISSUE THREAD

**Issue by alvanuffelen** [shenwei356/taxonkit#87]
### Prerequisites

- [x] make sure you're are using the latest version by `taxonkit version`
- [x] read the [usage](http://bioinf.shenwei.me/taxonkit/usage/)

### Describe your issue

`echo "Saccharomyces boulardii" | taxonkit name2taxid` gives no taxid output.
Looking in the `names.dmp`, 'Saccharomyces boulardii' can be found under:
 `252598      |       Saccharomyces boulardii |               |       equivalent name |`.

Is there a reason why 'name2taxid' only searches for scientific names or synonyms?
https://github.com/shenwei356/taxonkit/blob/571eda08f8554f5d98ee5c9ec2d607946807bd33/taxonkit/cmd/util-complex-data.go#L60

**Comment by shenwei356** [comment]
Just removed the restriction of name types.

- [taxonkit_darwin_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/12882655/taxonkit_darwin_amd64.tar.gz)
- [taxonkit_darwin_arm64.tar.gz](https://github.com/shenwei356/taxonkit/files/12882656/taxonkit_darwin_arm64.tar.gz)
- [taxonkit_linux_amd64.tar.gz](https://github.com/shenwei356/taxonkit/files/12882658/taxonkit_linux_amd64.tar.gz)
- [taxonkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/taxonkit/files/12882659/taxonkit_windows_amd64.exe.tar.gz)

```
$ memusg -t -s 'echo "Saccharomyces boulardii" | taxonkit name2taxid --verbose '
14:04:26.645 [INFO] parsing names file: /home/shenwei/.taxonkit/names.dmp
14:04:29.704 [INFO] 3895687 names parsed
Saccharomyces boulardii 252598

elapsed time: 3.187s
peak rss: 912.28 MB
```
