### ISSUE TITLE
convert taxdump from IMG/VR metadata

### ISSUE THREAD

**Issue by fgvieira** [shenwei356/taxonkit#94]
### Prerequisites

- [x] make sure you're are using the latest version by `taxonkit version`
- [x] read the [usage](http://bioinf.shenwei.me/taxonkit/usage/)

### Describe your issue

I am trying to read the `IMG/VR` metadata file and convert it to taxdump:
```
tail -n +2 IMGVR_all_Sequence_information-high_confidence.tsv | cut -f 1,15 | sed 's/;/\t/' | taxonkit create-taxdump --field-accession 1 --rank-names "realm","kingdom","phylum","class","order","family","genus","species" --out-dir imgvr-taxdump/
```
but the rank levels (i.e. `s__` or `g__`) are not parsed and are included in the `names.dmp`:
```
1       |       root    |               |       scientific name |
193620  |       s__Sukkupivirus idyn    |               |       scientific name |
474034  |       g__Moabitevirus |               |       scientific name |
755051  |       g__Kratiovirus  |               |       scientific name |
887735  |       s__Chiropteran bocaparvovirus 3 |               |       scientific name |
979430  |       s__Apricot pseudo-chlorotic leaf spot virus     |               |       scientific name |
1115513 |       s__Pegivirus G  |               |       scientific name |
2279768 |       s__Tinalinvirus tinalin |               |       scientific name |
2327733 |       g__Skarprettervirus     |               |       scientific name |
3024740 |       g__Sdenfavirus  |               |       scientific name |
3968924 |       s__Vicia cryptic virus  |               |       scientific name |
```

Since this format is similar to `GTDB` (see below), I thought of importing it directly:
```
tail -n +2 IMGVR_all_Sequence_information-high_confidence.tsv | cut -f 1,15 | taxonkit create-taxdump --field-accession 1 --gtdb --out-dir XXX-taxdump
```
but it fails, with:
```
14:51:56.936 [ERRO] invalid GTDB taxonomy format (kingdom): r__Monodnaviria
```

Is there a way to import this format directly? Just like for the `GTDB`, but allowing for other rank levels.

##### IMGVR_all_Sequence_information-high_confidence.tsv
```
UVIG	Taxon_oid	Scaffold_oid	Coordinates ('whole' if the UViG is the entire contig)	Ecosystem classification	vOTU	Length	Topology	geNomad score	Confidence	Estimated completeness	Estimated contamination	MIUViG quality	Gene content (total genes;cds;tRNA;geNomad marker)	Taxonomic classification	Taxonomic classification method	Host taxonomy prediction	Host prediction method	Sequence origin (doi)
IMGVR_UViG_2504643025_000001	2504643025	2504645545	381-5974	;;;	vOTU_00000001	5594	Provirus	0.9261	High-confidence	92.20	0.00	High-quality	10;10;0;5	r__Monodnaviria;k__Loebvirae;p__Hofneiviricota;c__Faserviricetes;o__Tubulavirales;;;	geNomad	d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Moraxellaceae;g__Acinetobacter;s__Acinetobacter baumannii	Isolate taxonomy	Inoviruses (10.1038/s41564-019-0510-x)
IMGVR_UViG_2504756089_000001	2504756089	2504826429	1745-11143	;;;	vOTU_00000002	9399	Provirus	0.6056	High-confidence	100.00	0.00	High-quality	16;16;0;5	r__Monodnaviria;k__Loebvirae;p__Hofneiviricota;c__Faserviricetes;o__Tubulavirales;f__Inoviridae;;	geNomad	d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__Salmonella;s__Salmonella enterica	Isolate taxonomy	Inoviruses (10.1038/s41564-019-0510-x)
IMGVR_UViG_2505313053_000001	2505313053	2505349123	1-7645	Host-associated;Plants;Phyllosphere;Leaf	vOTU_00000003	7645	Provirus	0.9234	High-confidence	100.00	0.00	High-quality	8;8;0;6	r__Monodnaviria;k__Loebvirae;p__Hofneiviricota;c__Faserviricetes;o__Tubulavirales;f__Inoviridae;;	geNomad	d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Pseudomonadaceae;g__Pseudomonas_E;s__Pseudomonas_E amygdali	Isolate taxonomy	Inoviruses (10.1038/s41564-019-0510-x)
IMGVR_UViG_2506210030_000001	2506210030	2506226343	whole	Host-associated;Unclassified;Unclassified;Unclassified	vOTU_00000004	10205	Linear	0.8570	High-confidence	100.00	0.00	High-quality	12;12;0;7	r__Monodnaviria;k__Loebvirae;p__Hofneiviricota;c__Faserviricetes;o__Tubulavirales;f__Inoviridae;;	geNomad	d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Pseudomonadaceae;g__Pseudomonas_E;s__Pseudomonas_E crudilactis	Isolate taxonomy	Inoviruses (10.1038/s41564-019-0510-x)
IMGVR_UViG_2507262023_000001	2507262023	2507275142	whole	Host-associated;Human;Respiratory system;Unclassified	vOTU_00000005	7392	Linear	0.9524	High-confidence	100.00	0.00	High-quality	10;10;0;8	r__Monodnaviria;k__Loebvirae;p__Hofneiviricota;c__Faserviricetes;o__Tubulavirales;f__Inoviridae;;	geNomad	d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Pseudomonadaceae;g__Pseudomonas;s__Pseudomonas aeruginosa	Isolate taxonomy	Inoviruses (10.1038/s41564-019-0510-x)
IMGVR_UViG_2507262024_000001	2507262024	2507276053	4006-13263	Host-associated;Unclassified;Unclassified;Unclassified	vOTU_00000006	9258	Provirus	0.9471	High-confidence	86.73	0.00	Genome fragment	11;11;0;8	r__Monodnaviria;k__Loebvirae;p__Hofneiviricota;c__Faserviricetes;o__Tubulavirales;f__Inoviridae;;	geNomad	d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Pseudomonadaceae;g__Pseudomonas;s__Pseudomonas aeruginosa	Isolate taxonomy	Inoviruses (10.1038/s41564-019-0510-x)
IMGVR_UViG_2510461032_000002	2510461032	2510473773	whole	Host-associated;Unclassified;Unclassified;Unclassified	vOTU_00000007	8497	Linear	0.6942	High-confidence	NA	0.00	Unsure	10;10;0;2	r__Monodnaviria;k__Loebvirae;p__Hofneiviricota;c__Faserviricetes;o__Tubulavirales;f__Inoviridae;;	NR (doi:10.5281/zenodo.6574914)	d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Pseudomonadaceae;g__Pseudomonas;s__Pseudomonas aeruginosa	Isolate taxonomy	Inoviruses (10.1038/s41564-019-0510-x)
IMGVR_UViG_2516653000_000001	2516653000	2516653193	690-7301	Environmental;Aquatic;Freshwater;Lotic	vOTU_00000008	6612	Provirus	0.6298	High-confidence	86.91	0.00	Genome fragment	9;9;0;3	r__Monodnaviria;k__Loebvirae;p__Hofneiviricota;c__Faserviricetes;o__Tubulavirales;;;	geNomad	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Xanthobacteraceae;g__Blastochloris;s__Blastochloris viridis	Isolate taxonomy	Inoviruses (10.1038/s41564-019-0510-x)
IMGVR_UViG_2516653000_000002	2516653000	2516653252	62-6062	Environmental;Aquatic;Freshwater;Lotic	vOTU_00000009	6001	Provirus	0.9261	High-confidence	83.15	0.00	Genome fragment	9;9;0;5	r__Monodnaviria;k__Loebvirae;p__Hofneiviricota;c__Faserviricetes;o__Tubulavirales;f__Inoviridae;;	geNomad	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Xanthobacteraceae;g__Blastochloris;s__Blastochloris viridis	Isolate taxonomy	Inoviruses (10.1038/s41564-019-0510-x)
```

**Comment by shenwei356** [comment]
Explore the data format with [csvtk](https://github.com/shenwei356/csvtk/releases/tag/v0.30.0).

    $ cat IMGVR_all_Sequence_information-high_confidence.tsv \
        | csvtk head -t -n 1 \
        | csvtk transpose -t \
        | csvtk pretty -Ht -W 50 -x ';' -Z

    1    UVIG                                                 IMGVR_UViG_2504643025_000001
    2    Taxon_oid                                            2504643025
    3    Scaffold_oid                                         2504645545
    4    Coordinates ('whole' if the UViG is the entire con   381-5974
        tig)
    5    Ecosystem classification                             ;;;
    6    vOTU                                                 vOTU_00000001
    7    Length                                               5594
    8    Topology                                             Provirus
    9    geNomad score                                        0.9261
    10   Confidence                                           High-confidence
    11   Estimated completeness                               92.20
    12   Estimated contamination                              0.00
    13   MIUViG quality                                       High-quality
    14   Gene content (total genes;cds;tRNA;geNomad marker)   10;10;0;5
    15   Taxonomic classification                             r__Monodnaviria;k__Loebvirae;p__Hofneiviricota;
                                                              c__Faserviricetes;o__Tubulavirales;;;
    16   Taxonomic classification method                      geNomad
    17   Host taxonomy prediction                             d__Bacteria;p__Proteobacteria;
                                                              c__Gammaproteobacteria;o__Pseudomonadales;
                                                              f__Moraxellaceae;g__Acinetobacter;
                                                              s__Acinetobacter baumannii
    18   Host prediction method                               Isolate taxonomy
    19   Sequence origin (doi)                                Inoviruses (10.1038/s41564-019-0510-x)

The 15th column should be the lineage, let's extract them and convert to a TSV format.


    $ sed 1d IMGVR_all_Sequence_information-high_confidence.tsv \
        | csvtk cut -Ht -f 1,15 \
        | csvtk sep -Ht -f 2 -s ';' -R \
        | csvtk replace -Ht -f 1- -p '^.__' \
        | head -n 2 \
        | csvtk pretty -Ht -S light

    ┌------------------------------┬--------------┬-----------┬----------------┬----------------┬---------------┬------------┬---┬---┐
    | IMGVR_UViG_2504643025_000001 | Monodnaviria | Loebvirae | Hofneiviricota | Faserviricetes | Tubulavirales |            |   |   |
    ├------------------------------┼--------------┼-----------┼----------------┼----------------┼---------------┼------------┼---┼---┤
    | IMGVR_UViG_2504756089_000001 | Monodnaviria | Loebvirae | Hofneiviricota | Faserviricetes | Tubulavirales | Inoviridae |   |   |
    └------------------------------┴--------------┴-----------┴----------------┴----------------┴---------------┴------------┴---┴---┘


Create the taxdump file.

    $ sed 1d IMGVR_all_Sequence_information-high_confidence.tsv \
        | csvtk cut -Ht -f 1,15 \
        | csvtk sep -Ht -f 2 -s ';' -R \
        | csvtk replace -Ht -f 1- -p '^.__' \
        | taxonkit create-taxdump --field-accession 1 --out-dir imgvr-taxdump/ \
            --rank-names "realm,kingdom,phylum,class,order,family,genus,species"

Test it

    $ cat IMGVR_all_Sequence_information-high_confidence.tsv \
        | csvtk grep -t -f 1 -p IMGVR_UViG_2504756089_000001 \
        | csvtk cut -t -f 1,15 \
        | csvtk pretty -t

    UVIG                           Taxonomic classification
    ----------------------------   -------------------------------------------------------------------------------------------------
    IMGVR_UViG_2504756089_000001   r__Monodnaviria;k__Loebvirae;p__Hofneiviricota;c__Faserviricetes;o__Tubulavirales;f__Inoviridae;;


    $ grep -w IMGVR_UViG_2504756089_000001 imgvr-taxdump/taxid.map \
        | taxonkit -i 2 -n -r lineage --data-dir imgvr-taxdump \
        | csvtk add-header -t -n ass,taxid,lineage,name,rank \
        | csvtk pretty -t -W 40 -x ';' -S light

    ┌------------------------------┬-----------┬------------------------------------------┬------------┬--------┐
    | ass                          | taxid     | lineage                                  | name       | rank   |
    ├==============================┼===========┼==========================================┼============┼========┤
    | IMGVR_UViG_2504756089_000001 | 313513884 | Monodnaviria;Loebvirae;Hofneiviricota;   | Inoviridae | family |
    |                              |           | Faserviricetes;Tubulavirales;Inoviridae  |            |        |
    └------------------------------┴-----------┴------------------------------------------┴------------┴--------┘
