### ISSUE TITLE
Exclude nodes from the taxonomy

### ISSUE THREAD

**Issue by fgvieira** [shenwei356/taxonkit#98]
Is it possible to remove a node (or a list of nodes) and (optionally) all those downstream? I am trying to remove all branches of the taxonomy that are unclassified (e.g. 12908).

Something like (when #93 is done):

```
echo unclassified | taxonkit name2taxid | taxonkit list | taxonkit filter --exclude | taxonkit create-taxdump
```

**Comment by shenwei356** [comment]
How about directly editing the `nodes.dmp` file.
1. get a list of ids with `taxonkit list` or other ways.
2. csvtk grep -Ht -f 1 -v -P list.txt nodes.dmp > nodes.new

**Comment by shenwei356** [comment]
How's it going?

**Comment by shenwei356** [comment]
Try it.
